### ISSUE TITLE
Project 1 Theory 2 Compiled: Denominator in Calculation

### ISSUE THREAD

**Issue by b-macdonald** [UniKerogen/TempleECE3712#7]
I don't understand the use of this in calculating R. For each individual E(_x, _y, _z), the distance R is just the distance from the chosen point to the current DS value. So, if the point is (2, 3, 4), and it is currently evaluating (0.05, 0.05, 0), the distance R for E_x is 1.95 (or -1.95). Maybe you could explain it a little more?

**Comment by b-macdonald** [comment]
For reference, my code generally goes like this:

```
for dx = deltax
   xxx = x - dx;
   E_1_x = E_1_x + sign(xxx) * (rho_S1 * S1_d) / (4 * pi * epsilon * xxx^2);
end
```

**Comment by UniKerogen** [comment]
As explained in the Explanation file, the function in the title is a simplified after the calculation. For different values, R^2 is always positive and |vector| is also positive, the sign will be reflected in the x,y,z component of the calculation, which is in the numerator instead of in the denominator.

**Comment by UniKerogen** [comment]
As future reference, the original title is:

"(X-X1(1,a))./(((X-X1(1,a))^2+(Y-Y1(b,1))^2+Z^2)^(3/2))"
